# -*- coding: utf-8 -*-
"""procfile

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pqM1dl6N1SWONzrwzlPnWDW5QNObUSWW
"""

pip install gunicorn

web gunicorn app:app

